### ISSUE TITLE
Where to find atmospheric library?

### ISSUE THREAD

**Issue by fhz-3722** [samsammurphy/gee-atmcorr-S2#14]
Hi author:

You import "atmospheric" library and use it to obtain aot parameters. But where to find this library? 

Thanks,
Hanze

**Comment by samsammurphy** [comment]
Hello,

It is within this repo

https://github.com/samsammurphy/gee-atmcorr-S2/blob/master/bin/atmospheric.py

It is imported by using sys to add the /bin directory to the path

```
# this adds the /bin directorty to the path
import sys
sys.path.append(os.path.join(os.path.dirname(os.getcwd()),'bin'))

# and this will find the atmospheric.py file mentioned above
from atmospheric import Atmospheric
```
