### ISSUE TITLE
Sentinel 3

### ISSUE THREAD

**Issue by jassantos** [samsammurphy/gee-atmcorr-S2#5]
Although the repo title may answer this question but I wanted to ask just to make sure. Is this applicable to Sentinel 3? Also what is the current condition of this? Is this properly working (properly doing atmospheric correction of S2 in gee)? 

I am unable to try this yet due to not being successful in installing the Python API of gee. Thanks.

**Comment by jassantos** [comment]
my questions got answered. I tried the code in your jupyter notebook earlier and its working fine for Sentinel 2 images. I tried working with Sentinel 3 images, however from what I have noticed, S3 images on GEE does not have data such as MEAN_SOLAR_ZENITH_ANGLE, which is needed by your code.

**Comment by samsammurphy** [comment]
Hi,

This repo is only designed for Sentinel 2. Glad it worked!

Sam

**Comment by jassantos** [comment]
Thanks!
