### ISSUE TITLE
how to run this program 

### ISSUE THREAD

**Issue by lizaoye** [samsammurphy/gee-atmcorr-S2#6]
Hi, Dr. Murphy, I am a student from China, I had download this program, but I can not run it correct, please help me how to run it correct, thank you very much

**Comment by samsammurphy** [comment]
Hiya @lizaoye :wave:   Thank you for opening this issue! I am now CEO of a company that we are building like crazy! This means I have no time to spend on other project, apologies!   I have updated the readme to warn others.  Thanks again!
