### ISSUE TITLE
Problem in function spectralResponseFunction()

### ISSUE THREAD

**Issue by GarudaGu** [samsammurphy/gee-atmcorr-S2#8]
We need to change the function to the following. Otherwise, an error will be reported 'PredefinedWavelengths' has no attribute 'S2A_MSI_13, because there is no B13 in S2A_MSI SRF (see the Py6S [source code](https://github.com/robintw/Py6S/blob/master/Py6S/Params/wavelength.py))

    def spectralResponseFunction(bandname):

    bandSelect = {
        'B1':PredefinedWavelengths.S2A_MSI_01,
        'B2':PredefinedWavelengths.S2A_MSI_02,
        'B3':PredefinedWavelengths.S2A_MSI_03,
        'B4':PredefinedWavelengths.S2A_MSI_04,
        'B5':PredefinedWavelengths.S2A_MSI_05,
        'B6':PredefinedWavelengths.S2A_MSI_06,
        'B7':PredefinedWavelengths.S2A_MSI_07,
        'B8':PredefinedWavelengths.S2A_MSI_08,
        'B8A':PredefinedWavelengths.S2A_MSI_8A,
        'B9':PredefinedWavelengths.S2A_MSI_09,
        'B10':PredefinedWavelengths.S2A_MSI_10,
        'B11':PredefinedWavelengths.S2A_MSI_11,
        'B12':PredefinedWavelengths.S2A_MSI_12,
        }
    return Wavelength(bandSelect[bandname])

**Comment by samsammurphy** [comment]
Thanks @GarudaGu 

Would you be open to make a Pull Request? :)

**Comment by samsammurphy** [comment]
Thanks @GarudaGu for the solution! Notebook now be fixed 🙌
